const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
const ARTICLES_FALIURE = 'ARTICLES_FALIURE';

export {
  ARTICLES_REQUEST,
  ARTICLES_SUCCESS,
  ARTICLES_FALIURE,
};
